---
title: "Triangle Regional Model Highway Metrics"
author: "Jacob Ford DCHC MPO"
output: 
  flexdashboard::flex_dashboard:
    theme: paper
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(xlsx)
library(readxl)
library(plotly)
library(sf)
library(dplyr)
library(tidygeocoder)
library(leaflet)
library(rgdal)
library(readxl)
library(sp)
library(ggplot2)
library(DT)
library(crosstalk)

pref_opt <- st_read("C:/Users/JacobFo/OneDrive - City of Durham/MTP Work/Pref Opt Hwy Line/Highway/Hwy Line.shp") 

pref_opt <-  pref_opt %>%
  select(ID, ROADNAME, COUNTY, FCGROUP, TOTDLYVOL, TOTAMVOL, TOTPMVOL, geometry)

pref_opt$COUNTY <- tolower(pref_opt$COUNTY)

temp <- pref_opt

trm_2016 <- st_read("C:/Users/JacobFo/OneDrive - City of Durham/Full Model Runs/Original TRMv6.2_2016 - Copy/Input/Highway/Hwy Line.shp")

trm_2016 <- trm_2016 %>%
  select(ID, ROADNAME, COUNTY, FCGROUP, TOTDLYVOL, TOTAMVOL, TOTPMVOL, geometry)

pref_opt <- SharedData$new(pref_opt)



```



Mapping {data-icon="ion-android-globe"}
=====================================  

Column {data-width=200}
-------------------------------------

### Filters

```{r filters}
bscols(


  filter_checkbox(
    id="FCGROUP_Input",
    label="Road Type",
    sharedData= pref_opt,
    group=~FCGROUP
  )

)

```





Column {data-width=350}
-----------------------------------------------------------------------

### Preferred Option 

```{r echo=FALSE, message=FALSE, warning=FALSE}

# add_fc_one <- pref_opt %>%
#   filter(FCGROUP==1)
# 
# add_fc_one <- st_as_sf(add_fc_one)
# 
# add_fc_two <- pref_opt %>%
#   filter(FCGROUP==2)
# 
# add_fc_three <- pref_opt %>%
#   filter(FCGROUP==3)
# 
# add_fc_four <- pref_opt %>%
#   filter(FCGROUP==4)
# 
# add_fc_five <- pref_opt %>%
#   filter(FCGROUP==5)
# 
# add_fc_999 <- pref_opt %>%
#   filter(FCGROUP==999)
  
bins <- c(0,1000,5000,20000, 50000,100000,200000)  

pal <- colorBin(
  palette = "YlOrRd", na.color = "#808080",
  bins=bins,
  domain = pref_opt$TOTDLYVOL)


a <- leaflet()%>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(data=pref_opt, color=~pal(TOTDLYVOL),  
              popup = paste("Road Name: ", pref_opt$ROADNAME , "<br>",
                            "Total Daily Volume: ", pref_opt$TOTDLYVOL
                            ),
              group="Freeways"
               
               )%>%


  addLayersControl(overlayGroups = c("Freeways", "Major Arterial", "Minor Arterial")) 



a %>% hideGroup("Major Arterial") %>% hideGroup("Minor Arterial")


```


Column {data-width=350}
-----------------------------------------------------------------------

### TRM 2016

```{r echo=FALSE, message=FALSE, warning=FALSE}



add_fc_one <- trm_2016 %>%
  filter(FCGROUP==1)

add_fc_one <- st_as_sf(add_fc_one)

add_fc_two <- trm_2016 %>%
  filter(FCGROUP==2)

add_fc_three <- trm_2016 %>%
  filter(FCGROUP==3)

add_fc_four <- trm_2016 %>%
  filter(FCGROUP==4)

add_fc_five <- trm_2016 %>%
  filter(FCGROUP==5)

add_fc_999 <- trm_2016 %>%
  filter(FCGROUP==999)
  
bins <- c(0,1000,5000,20000, 50000,100000,200000)  

pal <- colorBin(
  palette = "YlOrRd", na.color = "#808080",
  bins=bins,
  domain = pref_opt$TOTDLYVOL)


a <- leaflet()%>%
  addProviderTiles(providers$CartoDB.Positron) %>%
  addPolylines(data=add_fc_one, color=~pal(TOTDLYVOL),  
              popup = paste("Road Name: ", add_fc_one$ROADNAME , "<br>",
                            "Total Daily Volume: ", add_fc_one$TOTDLYVOL
                            ),
              group="Freeways"
               
               )%>%
    addPolylines(data=add_fc_two, color=~pal(TOTDLYVOL),  
              popup = paste("Road Name: ", add_fc_two$ROADNAME , "<br>",
                            "Total Daily Volume: ", add_fc_two$TOTDLYVOL
                            ),
              group="Major Arterial"
               
               )%>%
   addPolylines(data=add_fc_three, color=~pal(TOTDLYVOL),  
              popup = paste("Road Name: ", add_fc_three$ROADNAME , "<br>",
                            "Total Daily Volume: ", add_fc_three$TOTDLYVOL
                            ),
              group="Minor Arterial"
               
               )%>%
      addLegend("bottomright",
            pal=pal,
            value=trm_2016$TOTDLYVOL,
           # label="Black_2010",
            title="Total Daily Volume") %>%
  
  
  addLayersControl(overlayGroups = c("Freeways", "Major Arterial", "Minor Arterial")) 



a %>% hideGroup("Major Arterial") %>% hideGroup("Minor Arterial")

```



Graphs {data-icon="ion-stats-bars"}
=====================================  


Column {.tabset}
-----------------------------------------------------------------------

### Preferred Option Dly Vol by County

```{r echo=FALSE, message=FALSE, warning=FALSE}



temp <- temp %>%
  st_drop_geometry() %>%
  filter(COUNTY!="external") %>%
  group_by(COUNTY) %>%
  summarize(TOTDLYVOL = sum(TOTDLYVOL, na.rm=T)/1000000)



temp <- transform(temp,
                  COUNTY=reorder(COUNTY, -TOTDLYVOL))


p <- ggplot(temp, aes(x=COUNTY, y=TOTDLYVOL)) +
            geom_col(state='identity') + ggtitle("Preferred Option Total Daily Volume in Millions") + xlab("") 
ggplotly(p)


```


### TRM 2016 Dly Vol by County

```{r echo=FALSE, message=FALSE, warning=FALSE}

trm_2016$COUNTY <- tolower(trm_2016$COUNTY)

temp <- trm_2016 %>%
  st_drop_geometry() %>%
  filter(COUNTY!="external") %>%
  group_by(COUNTY) %>%
  summarize(TOTDLYVOL = sum(TOTDLYVOL, na.rm=T)/1000000)


temp <- transform(temp,
                  COUNTY=reorder(COUNTY, -TOTDLYVOL))


p <- ggplot(temp, aes(x=COUNTY, y=TOTDLYVOL)) +
            geom_col(state='identity') + ggtitle("TRM 2016 Total Daily Volume in Millions") + xlab("") 
ggplotly(p)


```

### Both Totl Dly Vol

```{r echo=FALSE, message=FALSE, warning=FALSE}


temp_one <- trm_2016 %>%
 # st_drop_geometry() %>%
  filter(COUNTY!="external") %>%
  group_by(COUNTY) %>%
  summarize(TOTDLYVOL = sum(TOTDLYVOL, na.rm=T)/1000000) %>%
  mutate(Scenario="BY")
temp_one <- temp_one[order(temp_one$COUNTY),]


temp_one<-temp_one[-1,]



temp_two <- pref_opt %>%
  st_drop_geometry() %>%
  filter(COUNTY!="external") %>%
  group_by(COUNTY) %>%
  summarize(TOTDLYVOL = sum(TOTDLYVOL, na.rm=T)/1000000) %>%
  mutate(Scenario="Preferred Option")

temp_two <- temp_two[order(temp_two$COUNTY),]


combined <- rbind(temp_one, temp_two)


combined <- transform(combined,
                  COUNTY=reorder(COUNTY, -TOTDLYVOL))


p <- ggplot(combined, aes(x=COUNTY, y=TOTDLYVOL, fill=Scenario)) +
            geom_col(state='identity',position='dodge') + ggtitle("TRM 2016 Total Daily Volume in Millions") + xlab("") 
ggplotly(p)


```